language: java

addons:
    apt:
        sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
        packages:
            - junit4
        
script:
    - cd JeuDuMenhir
    - ant MainJoueurTest
    
